---
- name: "Create Forwarding Domain and Flow Point"
  hosts: "5170_T5"
  connection: netconf
  gather_facts: false
  tasks:
      - name: "Read FD Variables"
        set_fact:
                 fds: "{{ lookup('template', 'templates/fdVars.yml') | from_yaml }}"
      - name: "Create FD"
        netconf_config:
            content: "{{ lookup('template', 'templates/createFd.j2') }}"           
        ignore_errors: True
      - name: "Read FP Name"
        set_fact:
               fps: "{{ lookup('template', 'templates/fpVars.yml') | from_yaml }}"
      - name: "Create FP"
        netconf_config:
            content: "{{ lookup('template', 'templates/createFp.j2') }}"
        ignore_errors: True

        
