---
- name: "Delete Maintenance Domain"
  hosts: "5170_T5"
  connection: netconf
  gather_facts: false
  tasks:
      - name: "Read MD Variables"
        set_fact:
                 mas: "{{ lookup('template', 'templates/MdVars.yml') | from_yaml }}"
      - name: "Delete MD"
        netconf_config:
            content: "{{ lookup('template', 'templates/deleteMd.j2') }}"           
        ignore_errors: True

        
