---
- name: "Create L2VPN-VPWS service"
  hosts: "5170_T2"
  connection: netconf
  gather_facts: false
  tasks:
          # - include_vars: /home/kathy/telesat/var.yml
      - name: "Read Variables"
        set_fact:
                 pws: "{{ lookup('template', 'templates/var2.yml') | from_yaml }}"
      - name: "Create Pseudowires"
        netconf_config:
            content: "{{ lookup('template', 'templates/createPw.j2') }}"           
        ignore_errors: True
        
