---
- name: "Delete Tunnels"
  hosts: "5170_T2"
  connection: netconf
  gather_facts: false
  tasks:
      - name: "Read Variables"
        set_fact:
                 tunnels: "{{ lookup('template', 'templates/tunnelVars.yml') | from_yaml }}"
      - name: "Delete Tunnels"
        netconf_config:
            content: "{{ lookup('template', 'templates/deleteTunnel.j2') }}"           
        ignore_errors: True

        
