---

- name: Interfaces
  hosts: "5170_T2"
  connection: netconf
  gather_facts: false
  tasks:
      - name: "TASK1: Get filtered output from switch"
        netconf_get:
                filter:  <maintenance-domain xmlns="http://metroethernetforum.org/ns/yang/mef-cfm">
                          <id>md3</id>
                           <maintenance-association>
                            <id>ma2001</id>
                            <maintenance-association-end-point>
                             <mep-identifier>2001</mep-identifier>
                             <loss-measurements xmlns="http://metroethernetforum.org/ns/yang/mef-soam-pm">
                              <loss-measurement>
                              </loss-measurement>
                             </loss-measurements>
                            </maintenance-association-end-point>
                           </maintenance-association>
                         </maintenance-domain>
        register: result
      - name: "TASK2: Format XML for easy viewing"
        xml:
          xmlstring: "{{ result.stdout }}"
          pretty_print: true
        register: pretty_config
        changed_when: false
      - name: "TASK3: Ensure output folder exists"
        file:
            path: "outputs"
            state: directory
        run_once: true
      - name: "TASK4: Write XML to disk"
        copy:
            content: "{{ pretty_config.xmlstring }}"
            dest: "outputs/{{inventory_hostname}}_mep_lm_netconf.xml"

